In [130]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from tqdm import tqdm
from sys import argv

In [131]:
df = pd.read_csv("../datasets/dataset_train.csv", index_col = "Index")

In [132]:
df

Hogwarts House First Name    Last Name    Birthday Best Hand  \
Index                                                                
0          Ravenclaw     Tamara          Hsu  2000-03-30      Left   
1          Slytherin      Erich      Paredes  1999-10-14     Right   
2          Ravenclaw   Stephany        Braun  1999-11-03      Left   
3         Gryffindor      Vesta    Mcmichael  2000-08-19      Left   
4         Gryffindor     Gaston        Gibbs  1998-09-27      Left   
...              ...        ...          ...         ...       ...   
1595      Gryffindor       Jung        Blank  2001-09-14     Right   
1596       Slytherin     Shelli         Lock  1998-03-12      Left   
1597      Gryffindor   Benjamin  Christensen  1999-10-24     Right   
1598      Hufflepuff  Charlotte       Dillon  2001-09-21      Left   
1599      Hufflepuff      Kylie        Nowak  2000-08-21      Left   

       Arithmancy   Astronomy  Herbology  Defense Against the Dark Arts  \
Index                                                                     
0         58384.0 -487.886086   5.727180                       4.878861   
1         67239.0 -552.060507  -5.987446                       5.520605   
2         23702.0 -366.076117   7.725017                       3.660761   
3         32667.0  697.742809  -6.497214                      -6.977428   
4         60158.0  436.775204  -7.820623                            NaN   
...           ...         ...        ...                            ...   
1595      49009.0  354.280086  -4.541837                      -3.542801   
1596      63296.0  367.531174   6.061064                      -3.675312   
1597      63905.0  544.018925  -3.203269                      -5.440189   
1598      82713.0  453.676219   3.442831                      -4.536762   
1599      48639.0  688.911989   5.421046                      -6.889120   

       Divination  Muggle Studies  Ancient Runes  History of Magic  \
Index                                                                
0           4.722      272.035831     532.484226          5.231058   
1          -5.612     -487.340557     367.760303          4.107170   
2           6.140      664.893521     602.585284          3.555579   
3           4.026     -537.001128     523.982133         -4.809637   
4           2.236     -444.262537     599.324514         -3.444377   
...           ...             ...            ...               ...   
1595        5.702     -497.235066     618.220213         -5.231721   
1596        1.757     -643.271092     445.827565          2.238112   
1597        6.065     -385.150457     635.211486         -5.984257   
1598        6.738     -831.741123     383.444937          3.813111   
1599        6.593     -234.207911     339.775154          7.208415   

       Transfiguration   Potions  Care of Magical Creatures     Charms  Flying  
Index                                                                           
0          1039.788281  3.790369                   0.715939 -232.79405  -26.89  
1          1058.944592  7.248742                   0.091674 -252.18425 -113.45  
2          1088.088348  8.728531                  -0.515327 -227.34265   30.42  
3           920.391449  0.821911                  -0.014040 -256.84675  200.64  
4           937.434724  4.311066                  -0.264070 -256.38730  157.98  
...                ...       ...                        ...        ...     ...  
1595        964.219853  3.389086                  -0.649983 -250.39401  185.83  
1596       1056.147366  5.825263                  -0.333962 -246.42719   44.80  
1597        953.866685  1.709808                   0.071569 -251.63679  198.47  
1598       1087.949205  3.904100                  -0.531875 -246.19072  -76.81  
1599       1034.928004  2.052215                   0.150532 -244.02063  -54.77  

[1600 rows x 18 columns]

In [133]:
df_bis = df.drop(['First Name', 'Last Name', "Birthday", "Best Hand"], axis=1, inplace=False)


In [134]:
df_bis.drop("Astronomy", axis=1, inplace=True)
df_bis.drop("Arithmancy", axis=1, inplace=True)
df_bis.drop("Care of Magical Creatures", axis=1, inplace=True)

In [135]:
df_bis

Hogwarts House  Herbology  Defense Against the Dark Arts  Divination  \
Index                                                                        
0          Ravenclaw   5.727180                       4.878861       4.722   
1          Slytherin  -5.987446                       5.520605      -5.612   
2          Ravenclaw   7.725017                       3.660761       6.140   
3         Gryffindor  -6.497214                      -6.977428       4.026   
4         Gryffindor  -7.820623                            NaN       2.236   
...              ...        ...                            ...         ...   
1595      Gryffindor  -4.541837                      -3.542801       5.702   
1596       Slytherin   6.061064                      -3.675312       1.757   
1597      Gryffindor  -3.203269                      -5.440189       6.065   
1598      Hufflepuff   3.442831                      -4.536762       6.738   
1599      Hufflepuff   5.421046                      -6.889120       6.593   

       Muggle Studies  Ancient Runes  History of Magic  Transfiguration  \
Index                                                                     
0          272.035831     532.484226          5.231058      1039.788281   
1         -487.340557     367.760303          4.107170      1058.944592   
2          664.893521     602.585284          3.555579      1088.088348   
3         -537.001128     523.982133         -4.809637       920.391449   
4         -444.262537     599.324514         -3.444377       937.434724   
...               ...            ...               ...              ...   
1595      -497.235066     618.220213         -5.231721       964.219853   
1596      -643.271092     445.827565          2.238112      1056.147366   
1597      -385.150457     635.211486         -5.984257       953.866685   
1598      -831.741123     383.444937          3.813111      1087.949205   
1599      -234.207911     339.775154          7.208415      1034.928004   

        Potions     Charms  Flying  
Index                               
0      3.790369 -232.79405  -26.89  
1      7.248742 -252.18425 -113.45  
2      8.728531 -227.34265   30.42  
3      0.821911 -256.84675  200.64  
4      4.311066 -256.38730  157.98  
...         ...        ...     ...  
1595   3.389086 -250.39401  185.83  
1596   5.825263 -246.42719   44.80  
1597   1.709808 -251.63679  198.47  
1598   3.904100 -246.19072  -76.81  
1599   2.052215 -244.02063  -54.77  

[1600 rows x 11 columns]

In [136]:
def describe(df):
    """
    Program that describe a dataset.
    """
    dfNum = df.select_dtypes(include=['int64','float64'])
    stats = pd.DataFrame(columns=dfNum.columns)
    col_name=stats.columns
    for i in range (len(stats.columns)):
        col = df.loc[:, col_name[i]]
        col_allNum = df.loc[~col.isna(), col_name[i]]
        count = len(col_allNum)
        mean = sum(col_allNum) / len(col_allNum)
        var =  sum([(x - mean)**2 for x in col_allNum])/count
        std = var**(0.5)
        stats.loc['Mean', col_name[i]] = mean
        stats.loc['Std', col_name[i]] = std
    return stats

In [137]:
stats = describe(df_bis)


In [138]:
stats

Herbology Defense Against the Dark Arts Divination Muggle Studies  \
Mean   1.14102                     -0.387863    3.15391    -224.589915   
Std   5.218016                      5.211132    4.15397     486.189433   

     Ancient Runes History of Magic Transfiguration   Potions      Charms  \
Mean     495.74797         2.963095     1030.096946  5.950373 -243.374409   
Std     106.251202         4.424353       44.111025  3.146852    8.780895   

         Flying  
Mean  21.958012  
Std   97.601087

In [139]:
def normalize_value(df):
    dfNum = df.select_dtypes(include=['int64','float64'])
    stats = describe(dfNum)
    dfN = df.copy()
    for i in range(len(dfNum.columns)):
        mean = stats.loc["Mean", dfNum.columns[i]]
        std = stats.loc["Std", dfNum.columns[i]]
        dfN.loc[:, dfNum.columns[i]] = (dfN.loc[:, dfNum.columns[i]] - mean) / std
    return dfN

In [140]:
df_Normilised = normalize_value(df_bis)

In [141]:
df_Normilised

Hogwarts House  Herbology  Defense Against the Dark Arts  Divination  \
Index                                                                        
0          Ravenclaw   0.878909                       1.010668    0.377492   
1          Slytherin  -1.366126                       1.133817   -2.110249   
2          Ravenclaw   1.261782                       0.776918    0.718852   
3         Gryffindor  -1.463820                      -1.264517    0.209941   
4         Gryffindor  -1.717442                            NaN   -0.220972   
...              ...        ...                            ...         ...   
1595      Gryffindor  -1.089084                      -0.605423    0.613411   
1596       Slytherin   0.942896                      -0.630851   -0.336283   
1597      Gryffindor  -0.832556                      -0.969526    0.700797   
1598      Hufflepuff   0.441128                      -0.796161    0.862811   
1599      Hufflepuff   0.820240                      -1.247571    0.827905   

       Muggle Studies  Ancient Runes  History of Magic  Transfiguration  \
Index                                                                     
0            1.021466       0.345749          0.512609         0.219703   
1           -0.540429      -1.204576          0.258586         0.653978   
2            1.829500       1.005516          0.133914         1.314669   
3           -0.642571       0.265730         -1.756806        -2.487031   
4           -0.451825       0.974827         -1.448228        -2.100659   
...               ...            ...               ...              ...   
1595        -0.560780       1.152667         -1.852207        -1.493438   
1596        -0.861148      -0.469834         -0.163862         0.590565   
1597        -0.330243       1.312583         -2.022296        -1.728145   
1598        -1.248796      -1.056958          0.192122         1.311515   
1599        -0.019782      -1.467963          0.959535         0.109520   

        Potions    Charms    Flying  
Index                                
0     -0.686402  1.204930 -0.500486  
1      0.412593 -1.003297 -1.387362  
2      0.882837  1.825755  0.086700  
3     -1.629712 -1.534279  1.830738  
4     -0.520936 -1.481955  1.393652  
...         ...       ...       ...  
1595  -0.813920 -0.799418  1.678998  
1596  -0.039757 -0.347662  0.234034  
1597  -1.347558 -0.940950  1.808504  
1598  -0.650260 -0.320732 -1.011956  
1599  -1.238749 -0.073594 -0.786139  

[1600 rows x 11 columns]

In [142]:
df_Normilised

Hogwarts House  Herbology  Defense Against the Dark Arts  Divination  \
Index                                                                        
0          Ravenclaw   0.878909                       1.010668    0.377492   
1          Slytherin  -1.366126                       1.133817   -2.110249   
2          Ravenclaw   1.261782                       0.776918    0.718852   
3         Gryffindor  -1.463820                      -1.264517    0.209941   
4         Gryffindor  -1.717442                            NaN   -0.220972   
...              ...        ...                            ...         ...   
1595      Gryffindor  -1.089084                      -0.605423    0.613411   
1596       Slytherin   0.942896                      -0.630851   -0.336283   
1597      Gryffindor  -0.832556                      -0.969526    0.700797   
1598      Hufflepuff   0.441128                      -0.796161    0.862811   
1599      Hufflepuff   0.820240                      -1.247571    0.827905   

       Muggle Studies  Ancient Runes  History of Magic  Transfiguration  \
Index                                                                     
0            1.021466       0.345749          0.512609         0.219703   
1           -0.540429      -1.204576          0.258586         0.653978   
2            1.829500       1.005516          0.133914         1.314669   
3           -0.642571       0.265730         -1.756806        -2.487031   
4           -0.451825       0.974827         -1.448228        -2.100659   
...               ...            ...               ...              ...   
1595        -0.560780       1.152667         -1.852207        -1.493438   
1596        -0.861148      -0.469834         -0.163862         0.590565   
1597        -0.330243       1.312583         -2.022296        -1.728145   
1598        -1.248796      -1.056958          0.192122         1.311515   
1599        -0.019782      -1.467963          0.959535         0.109520   

        Potions    Charms    Flying  
Index                                
0     -0.686402  1.204930 -0.500486  
1      0.412593 -1.003297 -1.387362  
2      0.882837  1.825755  0.086700  
3     -1.629712 -1.534279  1.830738  
4     -0.520936 -1.481955  1.393652  
...         ...       ...       ...  
1595  -0.813920 -0.799418  1.678998  
1596  -0.039757 -0.347662  0.234034  
1597  -1.347558 -0.940950  1.808504  
1598  -0.650260 -0.320732 -1.011956  
1599  -1.238749 -0.073594 -0.786139  

[1600 rows x 11 columns]

In [143]:
for i in range(len(df_Normilised.columns)):
    df_Normilised = df_Normilised.loc[~df_Normilised.isna()[df_Normilised.columns[i]], :]

# On ajoute les test
slytherin_df = df_Normilised.copy()
slytherin_df.loc[:, "Test Slytherin"] = 0
slytherin_df.loc[df.loc[:,"Hogwarts House"] == "Slytherin", "Test Slytherin"] = 1
ravenclaw_df= df_Normilised.copy()
ravenclaw_df.loc[:, "Test Ravenclaw"] = 0
ravenclaw_df.loc[df.loc[:,"Hogwarts House"] == "Ravenclaw", "Test Ravenclaw"] = 1
gryffindor_df= df_Normilised.copy()
gryffindor_df.loc[:, "Test Gryffindor"] = 0
gryffindor_df.loc[df_Normilised.loc[:,"Hogwarts House"] == "Gryffindor", "Test Gryffindor"] = 1
hufflepuff_df= df_Normilised.copy()
hufflepuff_df.loc[:, "Test Hufflepuff"] = 0
hufflepuff_df.loc[df_Normilised.loc[:,"Hogwarts House"] == "Hufflepuff", "Test Hufflepuff"] = 1
slytherin_df.drop("Hogwarts House", axis=1, inplace=True)
ravenclaw_df.drop("Hogwarts House", axis=1, inplace=True)
gryffindor_df.drop("Hogwarts House", axis=1, inplace=True)
hufflepuff_df.drop("Hogwarts House", axis=1, inplace=True)

X = slytherin_df.iloc[:, :len(slytherin_df.columns)-1]
y = np.array([slytherin_df.iloc[:, len(slytherin_df.columns)-1:].to_numpy()[:, 0],
        ravenclaw_df.iloc[:, len(ravenclaw_df.columns)-1:].to_numpy()[:, 0],
        gryffindor_df.iloc[:, len(gryffindor_df.columns)-1:].to_numpy()[:, 0],
        hufflepuff_df.iloc[:, len(hufflepuff_df.columns)-1:].to_numpy()[:, 0]])

In [144]:
alpha = 0.1
lambda_ = 0.1
nb_iterations = 200

In [145]:
X


Herbology  Defense Against the Dark Arts  Divination  Muggle Studies  \
Index                                                                         
0       0.878909                       1.010668    0.377492        1.021466   
1      -1.366126                       1.133817   -2.110249       -0.540429   
2       1.261782                       0.776918    0.718852        1.829500   
3      -1.463820                      -1.264517    0.209941       -0.642571   
5      -1.040667                       1.252076   -2.346168       -0.445110   
...          ...                            ...         ...             ...   
1595   -1.089084                      -0.605423    0.613411       -0.560780   
1596    0.942896                      -0.630851   -0.336283       -0.861148   
1597   -0.832556                      -0.969526    0.700797       -0.330243   
1598    0.441128                      -0.796161    0.862811       -1.248796   
1599    0.820240                      -1.247571    0.827905       -0.019782   

       Ancient Runes  History of Magic  Transfiguration   Potions    Charms  \
Index                                                                         
0           0.345749          0.512609         0.219703 -0.686402  1.204930   
1          -1.204576          0.258586         0.653978  0.412593 -1.003297   
2           1.005516          0.133914         1.314669  0.882837  1.825755   
3           0.265730         -1.756806        -2.487031 -1.629712 -1.534279   
5          -0.936894          0.546338         0.515704  1.843379 -0.520571   
...              ...               ...              ...       ...       ...   
1595        1.152667         -1.852207        -1.493438 -0.813920 -0.799418   
1596       -0.469834         -0.163862         0.590565 -0.039757 -0.347662   
1597        1.312583         -2.022296        -1.728145 -1.347558 -0.940950   
1598       -1.056958          0.192122         1.311515 -0.650260 -0.320732   
1599       -1.467963          0.959535         0.109520 -1.238749 -0.073594   

         Flying  
Index            
0     -0.500486  
1     -1.387362  
2      0.086700  
3      1.830738  
5     -0.580403  
...         ...  
1595   1.678998  
1596   0.234034  
1597   1.808504  
1598  -1.011956  
1599  -0.786139  

[1335 rows x 10 columns]

In [146]:
# def updateWb(X, y, w, b, lambda_, alpha):


In [147]:
def updateWb(X, y, w, b, lambda_, alpha):
    n = len(X)
    m = 1
    dj_dw = np.array([np.zeros(n), np.zeros(n), np.zeros(n), np.zeros(n)])
    dj_db = np.zeros(4)
    y_slytherin, y_ravenclaw, y_gryffindor, y_hufflepuff = y
    w_slytherin, w_ravenclaw, w_gryffindor, w_hufflepuff = w
    b_slytherin, b_ravenclaw, b_gryffindor, b_hufflepuff = b

    z_slytherin = np.dot(X.values, w_slytherin) + b_slytherin
    f_wb_i_slytherin = 1 / (1 + np.exp(-z_slytherin))
    err_i_slytherin  = f_wb_i_slytherin  - y_slytherin

    z_ravenclaw = np.dot(X.values, w_ravenclaw) + b_ravenclaw
    f_wb_i_ravenclaw = 1 / (1 + np.exp(-z_ravenclaw))
    err_i_ravenclaw  = f_wb_i_ravenclaw  - y_ravenclaw

    z_gryffindor = np.dot(X.values, w_gryffindor) + b_gryffindor
    f_wb_i_gryffindor = 1 / (1 + np.exp(-z_gryffindor))
    err_i_gryffindor  = f_wb_i_gryffindor  - y_gryffindor

    z_hufflepuff = np.dot(X.values, w_hufflepuff) + b_hufflepuff
    f_wb_i_hufflepuff = 1 / (1 + np.exp(-z_hufflepuff))
    err_i_hufflepuff = f_wb_i_hufflepuff  - y_hufflepuff
    X_arr = X.values
    for j in range(n):
        dj_dw[0][j] = dj_dw[0][j] + err_i_slytherin * X_arr[j]
        dj_dw[1][j] = dj_dw[1][j] + err_i_ravenclaw * X_arr[j]
        dj_dw[2][j] = dj_dw[2][j] + err_i_gryffindor * X_arr[j]
        dj_dw[3][j] = dj_dw[3][j] + err_i_hufflepuff * X_arr[j]
        dj_db[0] = dj_db[0] + err_i_slytherin
        dj_db[1] = dj_db[1] + err_i_ravenclaw
        dj_db[2] = dj_db[2] + err_i_gryffindor
        dj_db[3] = dj_db[3] + err_i_hufflepuff
    dj_dw =  dj_dw/m
    dj_db = dj_db/m

    for j in range(n):
        dj_dw[0][j] = dj_dw[0][j] + (lambda_/m) * w_slytherin[j]
        dj_dw[1][j] = dj_dw[1][j] + (lambda_/m) * w_ravenclaw[j]
        dj_dw[2][j] = dj_dw[2][j] + (lambda_/m) * w_gryffindor[j]
        dj_dw[3][j] = dj_dw[3][j] + (lambda_/m) * w_hufflepuff[j]

    W_updated = w - alpha * dj_dw
    b_updated = b - alpha * dj_db
    return (W_updated, b_updated)

In [148]:
# n = len(X.values)

# m = 1
# dj_dw = np.array([np.zeros(n), np.zeros(n), np.zeros(n), np.zeros(n)])
# dj_db = np.zeros(4)
# y_slytherin, y_ravenclaw, y_gryffindor, y_hufflepuff = y
# w_slytherin, w_ravenclaw, w_gryffindor, w_hufflepuff = w
# b_slytherin, b_ravenclaw, b_gryffindor, b_hufflepuff = b

# z_slytherin = np.dot(X.values, w_slytherin) + b_slytherin
# f_wb_i_slytherin = 1 / (1 + np.exp(-z_slytherin))
# err_i_slytherin  = f_wb_i_slytherin  - y_slytherin[0]

# z_ravenclaw = np.dot(X.values, w_ravenclaw) + b_ravenclaw
# f_wb_i_ravenclaw = 1 / (1 + np.exp(-z_ravenclaw))
# err_i_ravenclaw  = f_wb_i_ravenclaw  - y_ravenclaw[0]

# z_gryffindor = np.dot(X.values, w_gryffindor) + b_gryffindor
# f_wb_i_gryffindor = 1 / (1 + np.exp(-z_gryffindor))
# err_i_gryffindor  = f_wb_i_gryffindor  - y_gryffindor[0]

# z_hufflepuff = np.dot(X.values, w_hufflepuff) + b_hufflepuff
# f_wb_i_hufflepuff = 1 / (1 + np.exp(-z_hufflepuff))
# err_i_hufflepuff = f_wb_i_hufflepuff  - y_hufflepuff[0]

# print("z_slytherin", z_slytherin)
# print("f_wb_i_slytherin", f_wb_i_slytherin)
# print("err_i_slytherin", err_i_slytherin)



In [149]:
# X_arr = X.values
# for j in range(n):
#     print(err_i_slytherin)
#     dj_dw[0][j] = dj_dw[0][j] + err_i_slytherin * X_arr[j]
#     print("coucou")
#     dj_dw[1][j] = dj_dw[1][j] + err_i_ravenclaw * X_arr[j]
#     dj_dw[2][j] = dj_dw[2][j] + err_i_gryffindor * X_arr[j]
#     dj_dw[3][j] = dj_dw[3][j] + err_i_hufflepuff * X_arr[j]
#     #     dj_db[0] = dj_db[0] + err_i_slytherin
#     #     dj_db[1] = dj_db[1] + err_i_ravenclaw
#     #     dj_db[2] = dj_db[2] + err_i_gryffindor
#     #     dj_db[3] = dj_db[3] + err_i_hufflepuff
#     # print("coucou")
#     # dj_dw =  dj_dw/m
#     # dj_db = dj_db/m

#     # for j in range(n):
#     #     dj_dw[0][j] = dj_dw[0][j] + (lambda_/m) * w_slytherin[j]
#     #     dj_dw[1][j] = dj_dw[1][j] + (lambda_/m) * w_ravenclaw[j]
#     #     dj_dw[2][j] = dj_dw[2][j] + (lambda_/m) * w_gryffindor[j]
#     #     dj_dw[3][j] = dj_dw[3][j] + (lambda_/m) * w_hufflepuff[j]

#     # W_updated = w - alpha * dj_dw
#     # b_updated = b - alpha * dj_db
#     # return (W_updated, b_updated)

In [150]:
# dj_dw

In [151]:
m, n = X.shape
w = np.array([np.zeros(n), np.zeros(n), np.zeros(n), np.zeros(n)])
b = np.zeros(4)
result = np.array([np.zeros(nb_iterations), np.zeros(nb_iterations), np.zeros(nb_iterations), np.zeros(nb_iterations)])
for i in tqdm(range(nb_iterations)):
    y_to_use = np.array([y[0][i], y[1][i], y[2][i], y[3][i]])
    w, b = updateWb(X.iloc[i, :], y_to_use, w, b, lambda_, alpha)

  0%|          | 0/200 [00:00<?, ?it/s]/tmp/ipykernel_806758/2835429907.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(X[1])
100%|██████████| 200/200 [00:00<00:00, 1086.52it/s]

test
<class 'pandas.core.series.Series'>
1.0106679498502351
retc
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
0.5
coucou
0.5
coucou
0.5
coucou
0.5
coucou
0.5
coucou
0.5
coucou
0.5
coucou
0.5
coucou
0.5
coucou
0.5
coucou
coucou
test
<class 'pandas.core.series.Series'>
1.133816659568098
retc
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
-0.5945793974831511
coucou
-0.5945793974831511
coucou
-0.5945793974831511
coucou
-0.5945793974831511
coucou
-0.5945793974831511
coucou
-0.5945793974831511
coucou
-0.5945793974831511
coucou
-0.5945793974831511
coucou
-0.5945793974831511
coucou
-0.5945793974831511
coucou
coucou
test
<class 'pandas.core.series.Series'>
0.7769184247820302
retc
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
0.37072251324

In [152]:
w

array([[-0.42217491,  0.45942985, -0.68338776, -0.16999138, -0.24494975,
         0.09049759,  0.16921525,  0.47316332, -0.18109905, -0.23154485],
       [ 0.31522822,  0.46580016,  0.09216873,  0.71186452,  0.48984406,
         0.10080149,  0.13489952,  0.01209402,  0.55347503, -0.09511067],
       [-0.46740566, -0.19728074,  0.11438034, -0.12030333,  0.3901682 ,
        -0.54222317, -0.57735979, -0.15004341, -0.31029137,  0.53619665],
       [ 0.60285739, -0.72187265,  0.39636158, -0.50727272, -0.69758602,
         0.38679742,  0.33398031, -0.26192837, -0.09046756, -0.23433327]])

In [153]:
b

array([-2.5659092 , -1.81818629, -2.14846468, -0.83452544])

In [154]:
params = stats.copy()
params.loc["Slytherin", :] = w[0]
params.loc["Ravenclaw", :] = w[1]
params.loc["Gryffindor", :] = w[2]
params.loc["Hufflepuff", :] = w[3]
params.loc["Slytherin", "b"] = b[0]
params.loc["Ravenclaw", "b"] = b[1]
params.loc["Gryffindor", "b"] = b[2]
params.loc["Hufflepuff", "b"] = b[3]
params.to_csv("paramsStoch.csv", index=True)